export const ACTIVITIES_STORE = 'activitiesStore'
export const SESSION_STORE = 'sessionStore'
export const USER_STORE = 'userStore'
export const COMMENT_STORE = 'commentStore'
export const TRACK_STORE = 'trackStore'
export const PLAYER_STORE = 'playerStore'
export const PERFORMANCE_STORE = 'performanceStore'